-- たちばな祭2026 団体情報・初期化投入スクリプト
-- 生成日時: 2026/4/18 21:23:53

-- 既存データの全削除 (リレーションの都合上、子テーブルから削除)
DELETE FROM messages;
DELETE FROM performances;
DELETE FROM group_activities;
DELETE FROM groups;

-- データの投入
INSERT INTO groups (
  login_id, name, password, title, description, department, building, room, social_links,
  reception_status, waiting_time, ticket_status, 
  has_reception, has_waiting_time, has_ticket_status, has_performances,
  editing_locked
) VALUES
('1A', '1年A組', 'tachibana1A', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1B', '1年B組', 'tachibana1B', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1C', '1年C組', 'tachibana1C', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1D', '1年D組', 'tachibana1D', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1E', '1年E組', 'tachibana1E', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1F', '1年F組', 'tachibana1F', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1G', '1年G組', 'tachibana1G', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1H', '1年H組', 'tachibana1H', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('1I', '1年I組', 'tachibana1I', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2A', '2年A組', 'tachibana2A', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2B', '2年B組', 'tachibana2B', '', '', '食品', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2C', '2年C組', 'tachibana2C', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2D', '2年D組', 'tachibana2D', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2E', '2年E組', 'tachibana2E', '', '', '食品', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2F', '2年F組', 'tachibana2F', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2G', '2年G組', 'tachibana2G', '', '', '食品', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2H', '2年H組', 'tachibana2H', '', '', '食品', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('2I', '2年I組', 'tachibana2I', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('3A', '3年A組', 'tachibana3A', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3B', '3年B組', 'tachibana3B', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3C', '3年C組', 'tachibana3C', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3D', '3年D組', 'tachibana3D', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3E', '3年E組', 'tachibana3E', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3F', '3年F組', 'tachibana3F', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3G', '3年G組', 'tachibana3G', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3H', '3年H組', 'tachibana3H', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('3I', '3年I組', 'tachibana3I', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('funakogi', 'アコースティックギター部', 'guitar', 'ふなこぎライブ2026', 'アコースティックギターを用いた部員による演奏', '公演', '仮校舎', '', '{"instagram": "https://www.instagram.com/funako_acogi"}', 'open', 0, 'distributing', false, false, false, true, false),
('archery', 'アーチェリー部', 'yumi', 'アーチェリー体験', 'アーチェリーの試射体験', '体験, 食品', 'セミナー', '2階', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('english', '英語ディベート部', 'debate', '', '', '', '', '', '{}', 'open', 0, 'distributing', false, false, false, false, false),
('drama', '演劇部', 'masaka', '', '', '公演', '仮校舎', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('ensemble', 'オーケストラ部アンサンブル', 'music', '', '', '公演', '南館', '401', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('オーケストラ部全体', 'オーケストラ部全体', 'tachibanaオーケストラ部全体', 'オーケストラ部文化祭公演', 'オーケストラ部による演奏です♩♩船オケらしい華やかで明るい演奏をお届けします！', '公演', '体育館', '', '{"instagram": "https://www.instagram.com/kf_orchestra", "X": "https://x.com/funa_orche"}', 'open', 0, 'distributing', false, false, false, true, false),
('chorus', '合唱部', 'harmony', '', '', '公演', '南館', '401', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('flower', '華道部', 'arrange', '', '', '展示', '南館', '302', '{}', 'open', 0, 'distributing', false, false, false, false, false),
('quiz', 'クイズ研究会部', 'tachibanaquiz', '', '', '体験', '仮校舎', '', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('lmusic', '軽音楽部', 'ereki', '', '', '公演', 'セミナー', '3階', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('illust', '現代視覚研究部', 'tachibanaillust', '', '', '物販', '南館', '103', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('moshi', '県船模試 作成委員会(仮)', 'sundai', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('miyabi', '茶道部', 'tea-hanazawa', '雅', 'お客様をお席に招き、お点前を披露します。お抹茶と練り切りをお出しします。', '食品', '新館', '202', '{"instagram": "https://www.instagram.com/funabashi_sado"}', 'open', 0, 'distributing', true, true, false, false, false),
('nature', '自然科学部', 'tachibananature', '', '', '体験', '南館', '201', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('ジャグリング部', 'ジャグリング部', 'tachibanaジャグリング部', '', '', '公演', '体育館', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('photon', '写真部', 'camera', 'PHOTON', '部員の撮った選りすぐりの一枚を写真集にしました！写真展示もあります✨', '展示, 冊子, 物販', '南館', '204', '{"instagram": "https://www.instagram.com/kf_photoclub"}', 'open', 0, 'distributing', false, false, true, false, false),
('ジャスバンド部', 'ジャスバンド部', 'tachibanaジャスバンド部', '', '', '公演', '体育館', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('shogi', '将棋部', 'oute', '', '', '体験', '南館', '204', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('sumi', '書道部', 'suzuri', '', '', '', '', '', '{}', 'open', 0, 'distributing', false, false, false, false, false),
('council', '生徒会', 'senbei', '船高せんべい', 'ここでしか買うことのできない「船高せんべい」を今年も販売します。ぜひお買い求めください！', '食品', '南館', '105', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('sell', '生物部', 'animal', 'せ〜ぶつぶ', '生物部が飼っている生物を自由に見ることができます', '展示, 冊子', '南館', '101', '{"instagram": "https://www.instagram.com/funako_biology"}', 'open', 0, 'distributing', false, false, true, false, false),
('ソングリーディング部', 'ソングリーディング部', 'tachibanaソングリーディング部', 'Cheer up show !!', '演技を披露してお客さんに笑顔と元気を届けます！', '公演', '体育館', '', '{"instagram": "https://www.instagram.com/kf.nexus"}', 'open', 0, 'distributing', false, false, false, true, false),
('ダンス部', 'ダンス部', 'tachibanaダンス部', '', '', '公演', '体育館', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('地学部', '地学部', 'tachibana地学部', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('Deus Ex Machima', 'Deus Ex Machima', 'tachibanaDeus Ex Machima', '', '', '公演', '体育館', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('railway', '鐵道研究部', 'train', '', '', '', '', '', '{}', 'open', 0, 'distributing', false, false, false, false, false),
('clay', '陶芸部', 'tachibanaclay', '', '', '展示, 物販', '新館', '101', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('library', '図書委員会', 'book', '', '', '展示, 物販', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('badminton', 'バドミントン部', 'bread', '', '', '食品', 'セミナー', '1階', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('art', '美術部', 'tachibanaart', '', '', '展示, 物販', '南館', '103', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('FUNATUNE', 'FUNATUNE', 'tachibanaFUNATUNE', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('文芸同好会', '文芸同好会', 'tachibana文芸同好会', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('ブーンプロジェクト', 'ブーンプロジェクト', 'tachibanaブーンプロジェクト', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('理数科結合', '理数科結合', 'tachibana理数科結合', '', '', '冊子', '南館', '204', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('pta', '船橋高校PTA', 'atp', '', '', '物販', '南館', '105', '{}', 'open', 0, 'distributing', false, false, true, false, false),
('field', '陸上競技部', 'track', '', '', '食品', '南館', '102', '{}', 'open', 0, 'distributing', true, true, false, false, false),
('吹奏楽連合', '吹奏楽連合', 'tachibana吹奏楽連合', '', '', '公演', '体育館', '', '{}', 'open', 0, 'distributing', false, false, false, true, false),
('文化委員会', '文化委員会', 'tachibana文化委員会', '文化委員会本部', 'スタンプラリー景品引換、落とし物受取', '', '仮校舎', '東201', '{}', 'open', 0, 'distributing', false, false, false, false, false);
